---
title: "Just a simple reminder to water plants"
author: "Lisa Anders"
date: '2022-05-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This is a document that runs on Connect and sends me an email. Based on the 2022-02-24 Inside Look `Connecting on Connect` by Kelly. Thanks Kelly!  

 - [Inside Look including Connecting on Connect by Kelly](https://app.tettra.co/teams/rstudio/pages/inside-look-series)
 - [Jokes from kidadl](https://kidadl.com/funnies/jokes/best-plant-jokes-that-youll-be-very-frond-of)
 - [Image from shutterstock](https://www.shutterstock.com/image-vector/cute-boy-watering-plant-pixel-art-1262641045)
 
Want to make this page yourself? Check out these resources: 

 - [blastula solutions article](https://solutions.rstudio.com/r/blastula/)
 - [blastula github](https://github.com/rstudio/blastula)
 - [getting started with blastula](https://rstudio.github.io/blastula/articles/blastula.html)


```{r}
library(blastula)

jokes <- c(
"What did one flower say to the other? What's up bud?",
"What kind of flower grows on your face? Tulips!",
"What did the bee say to the flower? Hello honey!",
"Why do flowers always drive so fast? They put the petal to the metal!",
"Did you hear about the two flowers who went on a date? It's a budding romance!",
"What did the flower study in college? STEM!",
"Why are flowers so good at problem solving? They know how to nip it in the bud!",
"What does a flower say when it's surprised? What in carnation?!",
"What do you call a flower that runs on electricity? A power plant!",
"What is Spring's favourite kind of pickle? Daffo-dills!")

img_file_path <-
  system.file(
    "img", "image_plant.JPG",
    package = "blastula"
  )

img_string <- add_image(file = img_file_path)

email <-
  compose_email(
    body = md(glue::glue(
"Hey you,

It's been 2 weeks - don't forget to water the plants!

{img_string}
")),
    footer = md(glue::glue("Email sent on {date_time}."))
  )


attach_connect_email(
 subject = sample(jokes,1), 
 text = email
)
```

```{r, eval=TRUE}
# This section is for previewing the html and is for development only
#knitr::kable(html, escape = TRUE)

# Preview the email
#email
```